import { createContext, useContext, useState, ReactNode } from "react";

type Language = "tr" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.team": "Takım",
    "nav.vehicle": "Araç",
    "nav.sponsors": "Sponsorlar",
    "nav.contact": "İletişim",
    
    // Footer
    "footer.description": "Doğu Akdeniz Üniversitesi Formula Student Takımı",
    "footer.quickLinks": "Hızlı Bağlantılar",
    "footer.contactTitle": "İletişim",
    "footer.address": "Doğu Akdeniz Üniversitesi\nGazimağusa, KKTC",
    "footer.copyright": "© 2026 EMUFSC. Tüm hakları saklıdır.",
    
    // Home Page
    "home.hero.title": "Formula Student Takımı",
    "home.hero.description": "Mühendislik tutkusu ile elektrikli araç teknolojilerini birleştiren yeni kurulan öğrenci ekibimiz, geleceğin sürdürülebilir motorsporunu bugünden şekillendiriyor.",
    "home.hero.cta1": "Takımımızı Keşfedin",
    "home.hero.cta2": "Bize Katılın",
    "home.stats.members": "Takım Üyesi",
    "home.stats.year": "Yıl (2026'da Kurulduk)",
    "home.stats.project": "İlk Elektrikli Araç Projesi",
    "home.about.title": "Biz",
    "home.about.titleHighlight": "Kimiz?",
    "home.about.p1": "EMUFSC, Doğu Akdeniz Üniversitesi öğrencilerinden oluşan yeni ve dinamik bir Formula Student takımıdır. 2026 yılında kurulan takımımız, elektrikli araç teknolojileri üzerine yoğunlaşarak, teorik bilgiyi pratiğe dönüştürme hedefiyle yola çıktı.",
    "home.about.p2": "İlk elektrikli yarış aracımızı sıfırdan tasarlamak ve üretmek için çalışıyoruz. Mekanik, elektrik-elektronik, yazılım ve işletme alanlarındaki öğrencilerimiz, gerçek dünya mühendislik problemlerini çözerek kariyer yolculuklarına en iyi şekilde hazırlanıyorlar.",
    "home.about.link": "Daha Fazla Bilgi",
    "home.news.title": "Son",
    "home.news.titleHighlight": "Haberler",
    "home.news.1.title": "EMUFSC Takımı Kuruldu",
    "home.news.1.date": "1 Mart 2026",
    "home.news.2.title": "İlk Toplantımız Gerçekleşti",
    "home.news.2.date": "5 Mart 2026",
    "home.news.3.title": "Yeni Üye Alımları Başladı",
    "home.news.3.date": "8 Mart 2026",
    "home.news.readMore": "Devamını Oku",
    "home.cta.title": "Takımımıza",
    "home.cta.titleHighlight": "Katılın!",
    "home.cta.description": "Elektrikli araç teknolojilerine ilgi duyan, mühendislik tutkusu taşıyan ve takım çalışmasına yatkın öğrencileri aramıza bekliyoruz.",
    "home.cta.button": "Bize Ulaşın",
    
    // Team Page
    "team.hero.title": "Bizim",
    "team.hero.titleHighlight": "Takımımız",
    "team.hero.description": "Farklı disiplinlerden gelen tutkulu öğrencilerin bir araya geldiği, öğrenme ve gelişim odaklı yeni bir topluluk.",
    "team.story.title": "Hikaye",
    "team.story.titleHighlight": "miz",
    "team.story.p1": "EMUFSC, 2026 yılında bir grup mühendislik öğrencisinin hayalini gerçeğe dönüştürme arzusuyla kuruldu. Elektrikli araç teknolojilerine olan tutkumuz ve Formula Student yarışmalarının sunduğu benzersiz öğrenme fırsatları bizi bir araya getirdi.",
    "team.story.p2": "Yeni kurulmuş bir takım olarak, ilk elektrikli yarış aracımızı tasarlama ve üretme yolculuğundayız. Her gün yeni şeyler öğreniyor, kendimizi geliştiriyor ve bir sonraki adıma hazırlanıyoruz.",
    "team.story.p3": "Amacımız sadece yarışmak değil; üyelerimize gerçek dünya mühendislik deneyimi kazandırarak, geleceğin sürdürülebilir otomotiv sektörü liderlerini yetiştirmek.",
    "team.departments.title": "Depart",
    "team.departments.titleHighlight": "manlar",
    "team.dept.mechanical": "Mekanik",
    "team.dept.mechanical.desc": "Şasi, süspansiyon ve aerodinamik tasarımından sorumlu ekibimiz.",
    "team.dept.electrical": "Elektrik-Elektronik",
    "team.dept.electrical.desc": "Batarya sistemleri, motor kontrolcüleri ve elektronik devrelerini geliştiren ekibimiz.",
    "team.dept.software": "Yazılım",
    "team.dept.software.desc": "Veri toplama, telemetri ve araç kontrol yazılımlarını kodlayan ekibimiz.",
    "team.dept.business": "İşletme",
    "team.dept.business.desc": "Sponsorluk, pazarlama ve organizasyon süreçlerini yöneten ekibimiz.",
    "team.dept.members": "üye",
    "team.values.title": "Değer",
    "team.values.titleHighlight": "lerimiz",
    "team.value.excellence": "Mükemmellik",
    "team.value.excellence.desc": "Her detayda en yüksek kalite standardını hedefliyoruz.",
    "team.value.teamwork": "Takım Ruhu",
    "team.value.teamwork.desc": "Birlikte çalışarak daha büyük başarılara ulaşıyoruz.",
    "team.value.innovation": "İnovasyon",
    "team.value.innovation.desc": "Sürekli öğrenerek ve yenilik yaparak ilerliyoruz.",
    "team.join.title": "Bize Katılmak İster Misiniz?",
    "team.join.description": "Yeni kurulmuş takımımıza katılarak ilk elektrikli aracımızın tasarımında ve üretiminde aktif rol alın! Mühendislik, işletme veya tasarım alanında ilgi duyuyor ve takım çalışmasını seviyorsanız, sizi aramızda görmek isteriz!",
    "team.join.cta1": "İletişime Geçin",
    "team.join.cta2": "Başvuru Formu",
    
    // Vehicle Page
    "vehicle.hero.title": "İlk Elektrikli Aracımız",
    "vehicle.hero.description": "2027 sezonunda yarışlarda görmek için tasarlamakta olduğumuz elektrikli formula aracımız.",
    "vehicle.concept.title": "Konsept",
    "vehicle.concept.titleHighlight": "Tasarım",
    "vehicle.concept.description": "Yeni kurulmuş bir takım olarak, şu anda ilk elektrikli yarış aracımızın konsept tasarımı üzerinde çalışıyoruz. Ekibimiz, en iyi performans ve verimliliği sağlamak için araştırma ve planlama aşamasındadır.",
    "vehicle.features.title": "Hedeflenen",
    "vehicle.features.titleHighlight": "Özellikler",
    "vehicle.feature.monocoque": "Hafif Karbon Fiber Şasi",
    "vehicle.feature.monocoque.desc": "Maksimum güvenlik ve minimum ağırlık için karbon fiber kompozit monokok şasi tasarlıyoruz.",
    "vehicle.feature.electric": "Elektrikli Güç Ünitesi",
    "vehicle.feature.electric.desc": "Yüksek verimli elektrik motorları ve akıllı batarya yönetim sistemi ile çevre dostu, güçlü bir araç hedefliyoruz.",
    "vehicle.feature.aero": "Aerodinamik Optimizasyon",
    "vehicle.feature.aero.desc": "CFD simülasyonları ile optimize edilmiş kanat ve difüzör tasarımı üzerinde çalışıyoruz.",
    "vehicle.timeline.title": "Gelişim",
    "vehicle.timeline.titleHighlight": "Yol Haritası",
    "vehicle.phase.research": "Araştırma & Planlama",
    "vehicle.phase.research.period": "Mart - Mayıs 2026",
    "vehicle.phase.research.desc": "Pazar araştırması, konsept geliştirme ve tasarım parametrelerinin belirlenmesi.",
    "vehicle.phase.design": "Tasarım",
    "vehicle.phase.design.period": "Haziran - Eylül 2026",
    "vehicle.phase.design.desc": "CAD modellemesi, simülasyonlar ve detaylı mühendislik analizi.",
    "vehicle.phase.production": "Üretim",
    "vehicle.phase.production.period": "Ekim 2026 - Mart 2027",
    "vehicle.phase.production.desc": "Parça imalatı, montaj ve sistem entegrasyonu.",
    "vehicle.phase.testing": "Test & Yarışma",
    "vehicle.phase.testing.period": "Nisan - Ağustos 2027",
    "vehicle.phase.testing.desc": "Testler, optimizasyon ve Formula Student yarışmaları.",
    "vehicle.join.title": "Projeye Dahil Olun",
    "vehicle.join.description": "İlk elektrikli aracımızın tasarım ve üretim sürecinde yer almak ister misiniz? Hemen başvurun!",
    "vehicle.join.button": "Takıma Katıl",
    
    // Sponsors Page
    "sponsors.hero.title": "Sponsor",
    "sponsors.hero.titleHighlight": "larımız",
    "sponsors.hero.description": "Hayallerimizi gerçekleştirmemizde bizlere destek olan değerli iş ortaklarımızı arıyoruz.",
    "sponsors.tiers.platinum": "Platin Sponsorlar",
    "sponsors.tiers.gold": "Altın Sponsorlar",
    "sponsors.tiers.silver": "Gümüş Sponsorlar",
    "sponsors.looking": "Sponsor Arıyoruz!",
    "sponsors.looking.desc": "Yeni kurulmuş takımımızın ilk elektrikli aracını gerçeğe dönüştürmek için sponsorlara ihtiyacımız var.",
    "sponsors.why.title": "Neden",
    "sponsors.why.titleHighlight": "Sponsor",
    "sponsors.why.subtitle": "Olmalısınız?",
    "sponsors.why.description": "EMUFSC'ye sponsor olmak, yalnızca bir takımı desteklemek değil, geleceğe yatırım yapmak demektir.",
    "sponsors.benefit.visibility": "Marka Görünürlüğü",
    "sponsors.benefit.visibility.desc": "Aracımız, takım kıyafetleri ve sosyal medyada markanızı sergileyin.",
    "sponsors.benefit.csr": "Kurumsal Sosyal Sorumluluk",
    "sponsors.benefit.csr.desc": "Eğitime ve sürdürülebilir teknolojilere destek vererek sorumluluğunuzu gösterin.",
    "sponsors.benefit.networking": "Networking Fırsatları",
    "sponsors.benefit.networking.desc": "Yarışmalarda ve etkinliklerde sektör profesyonelleriyle tanışın.",
    "sponsors.benefit.talent": "Yetenek Kaynağı",
    "sponsors.benefit.talent.desc": "Gelecek vaat eden mühendislik öğrencileriyle erken temas kurun.",
    "sponsors.packages.title": "Sponsorluk",
    "sponsors.packages.titleHighlight": "Paketleri",
    "sponsors.packages.description": "İhtiyaçlarınıza ve bütçenize uygun farklı sponsorluk seçenekleri sunuyoruz.",
    "sponsors.package.popular": "En Popüler",
    "sponsors.cta.title": "Bizimle İletişime Geçin",
    "sponsors.cta.description": "Sponsorluk fırsatları hakkında daha fazla bilgi almak ve geleceğin elektrikli otomotiv liderleriyle işbirliği yapmak için ekibimizle görüşün.",
    "sponsors.cta.form": "İletişim Formu",
    "sponsors.cta.email": "Email Gönderin",
    "sponsors.impact.title": "Sponsor Desteğinin",
    "sponsors.impact.titleHighlight": "Etkisi",
    "sponsors.impact.students": "Öğrenci Eğitimi",
    "sponsors.impact.reach": "Sosyal Medya Erişimi",
    "sponsors.impact.project": "Elektrikli Araç Projesi",
    
    // Contact Page
    "contact.hero.title": "İletişime",
    "contact.hero.titleHighlight": "Geçin",
    "contact.hero.description": "Sorularınız, önerileriniz veya işbirliği teklifleriniz için bizimle iletişime geçmekten çekinmeyin.",
    "contact.info.address": "Adres",
    "contact.info.email": "Email",
    "contact.info.phone": "Telefon",
    "contact.form.title": "Bize",
    "contact.form.titleHighlight": "Yazın",
    "contact.form.name": "Adınız Soyadınız",
    "contact.form.email": "Email Adresiniz",
    "contact.form.subject": "Konu",
    "contact.form.subject.select": "Konu seçin",
    "contact.form.subject.general": "Genel Bilgi",
    "contact.form.subject.membership": "Üyelik",
    "contact.form.subject.sponsorship": "Sponsorluk",
    "contact.form.subject.media": "Medya & Basın",
    "contact.form.subject.other": "Diğer",
    "contact.form.message": "Mesajınız",
    "contact.form.submit": "Mesaj Gönder",
    "contact.form.success": "Mesajınız alındı! En kısa sürede size dönüş yapacağız.",
    "contact.quick.title": "Hızlı",
    "contact.quick.titleHighlight": "Bilgiler",
    "contact.hours.title": "Çalışma Saatleri",
    "contact.hours.weekday": "Pazartesi - Cuma: 09:00 - 18:00",
    "contact.hours.saturday": "Cumartesi: 10:00 - 16:00",
    "contact.hours.sunday": "Pazar: Kapalı",
    "contact.visit.title": "Atölyemizi Ziyaret Edin",
    "contact.visit.description": "Takımımızı ve çalışmalarımızı yakından görmek isterseniz, lütfen önceden randevu alın. Size gezinti yaptırmaktan ve projelerimizi anlatmaktan mutluluk duyarız.",
    "contact.visit.button": "Randevu Al →",
    "contact.social.title": "Sosyal Medya",
    "contact.location.title": "Konum",
    "contact.location.titleHighlight": "umuz",
    "contact.faq.title": "Sık Sorulan",
    "contact.faq.titleHighlight": "Sorular",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.team": "Team",
    "nav.vehicle": "Vehicle",
    "nav.sponsors": "Sponsors",
    "nav.contact": "Contact",
    
    // Footer
    "footer.description": "Eastern Mediterranean University Formula Student Team",
    "footer.quickLinks": "Quick Links",
    "footer.contactTitle": "Contact",
    "footer.address": "Eastern Mediterranean University\nFamagusta, North Cyprus",
    "footer.copyright": "© 2026 EMUFSC. All rights reserved.",
    
    // Home Page
    "home.hero.title": "Formula Student Team",
    "home.hero.description": "Our newly established student team combines engineering passion with electric vehicle technologies, shaping tomorrow's sustainable motorsport today.",
    "home.hero.cta1": "Discover Our Team",
    "home.hero.cta2": "Join Us",
    "home.stats.members": "Team Members",
    "home.stats.year": "Year (Founded in 2026)",
    "home.stats.project": "First Electric Vehicle Project",
    "home.about.title": "Who",
    "home.about.titleHighlight": "We Are?",
    "home.about.p1": "EMUFSC is a new and dynamic Formula Student team consisting of Eastern Mediterranean University students. Founded in 2026, our team set out with the goal of transforming theoretical knowledge into practice, focusing on electric vehicle technologies.",
    "home.about.p2": "We are working to design and build our first electric racing car from scratch. Our students from mechanical, electrical-electronics, software, and business fields are preparing for their career journeys in the best way by solving real-world engineering problems.",
    "home.about.link": "Learn More",
    "home.news.title": "Latest",
    "home.news.titleHighlight": "News",
    "home.news.1.title": "EMUFSC Team Founded",
    "home.news.1.date": "March 1, 2026",
    "home.news.2.title": "First Team Meeting Held",
    "home.news.2.date": "March 5, 2026",
    "home.news.3.title": "New Member Recruitment Started",
    "home.news.3.date": "March 8, 2026",
    "home.news.readMore": "Read More",
    "home.cta.title": "Join",
    "home.cta.titleHighlight": "Our Team!",
    "home.cta.description": "We are looking for students interested in electric vehicle technologies, passionate about engineering, and inclined towards teamwork.",
    "home.cta.button": "Contact Us",
    
    // Team Page
    "team.hero.title": "Our",
    "team.hero.titleHighlight": "Team",
    "team.hero.description": "A new community focused on learning and development, bringing together passionate students from different disciplines.",
    "team.story.title": "Our",
    "team.story.titleHighlight": "Story",
    "team.story.p1": "EMUFSC was founded in 2026 with the desire of a group of engineering students to make their dreams come true. Our passion for electric vehicle technologies and the unique learning opportunities offered by Formula Student competitions brought us together.",
    "team.story.p2": "As a newly established team, we are on a journey to design and build our first electric racing car. We learn new things every day, improve ourselves, and prepare for the next step.",
    "team.story.p3": "Our goal is not just to compete; it is to train the leaders of tomorrow's sustainable automotive industry by providing our members with real-world engineering experience.",
    "team.departments.title": "Depart",
    "team.departments.titleHighlight": "ments",
    "team.dept.mechanical": "Mechanical",
    "team.dept.mechanical.desc": "Our team responsible for chassis, suspension, and aerodynamic design.",
    "team.dept.electrical": "Electrical-Electronics",
    "team.dept.electrical.desc": "Our team developing battery systems, motor controllers, and electronic circuits.",
    "team.dept.software": "Software",
    "team.dept.software.desc": "Our team coding data acquisition, telemetry, and vehicle control software.",
    "team.dept.business": "Business",
    "team.dept.business.desc": "Our team managing sponsorship, marketing, and organizational processes.",
    "team.dept.members": "members",
    "team.values.title": "Our",
    "team.values.titleHighlight": "Values",
    "team.value.excellence": "Excellence",
    "team.value.excellence.desc": "We aim for the highest quality standards in every detail.",
    "team.value.teamwork": "Teamwork",
    "team.value.teamwork.desc": "We achieve greater success by working together.",
    "team.value.innovation": "Innovation",
    "team.value.innovation.desc": "We progress by continuously learning and innovating.",
    "team.join.title": "Want to Join Us?",
    "team.join.description": "Join our newly established team and take an active role in the design and production of our first electric vehicle! If you are interested in engineering, business, or design and enjoy teamwork, we would love to have you with us!",
    "team.join.cta1": "Get in Touch",
    "team.join.cta2": "Application Form",
    
    // Vehicle Page
    "vehicle.hero.title": "Our First Electric Vehicle",
    "vehicle.hero.description": "Our electric formula car that we are designing to see in competitions in the 2027 season.",
    "vehicle.concept.title": "Concept",
    "vehicle.concept.titleHighlight": "Design",
    "vehicle.concept.description": "As a newly established team, we are currently working on the concept design of our first electric racing car. Our team is in the research and planning phase to ensure the best performance and efficiency.",
    "vehicle.features.title": "Target",
    "vehicle.features.titleHighlight": "Features",
    "vehicle.feature.monocoque": "Lightweight Carbon Fiber Chassis",
    "vehicle.feature.monocoque.desc": "We are designing a carbon fiber composite monocoque chassis for maximum safety and minimum weight.",
    "vehicle.feature.electric": "Electric Powertrain",
    "vehicle.feature.electric.desc": "We aim for an environmentally friendly, powerful vehicle with highly efficient electric motors and smart battery management system.",
    "vehicle.feature.aero": "Aerodynamic Optimization",
    "vehicle.feature.aero.desc": "We are working on wing and diffuser designs optimized through CFD simulations.",
    "vehicle.timeline.title": "Development",
    "vehicle.timeline.titleHighlight": "Roadmap",
    "vehicle.phase.research": "Research & Planning",
    "vehicle.phase.research.period": "March - May 2026",
    "vehicle.phase.research.desc": "Market research, concept development, and determination of design parameters.",
    "vehicle.phase.design": "Design",
    "vehicle.phase.design.period": "June - September 2026",
    "vehicle.phase.design.desc": "CAD modeling, simulations, and detailed engineering analysis.",
    "vehicle.phase.production": "Production",
    "vehicle.phase.production.period": "October 2026 - March 2027",
    "vehicle.phase.production.desc": "Part manufacturing, assembly, and system integration.",
    "vehicle.phase.testing": "Testing & Competition",
    "vehicle.phase.testing.period": "April - August 2027",
    "vehicle.phase.testing.desc": "Tests, optimization, and Formula Student competitions.",
    "vehicle.join.title": "Join the Project",
    "vehicle.join.description": "Do you want to be involved in the design and production process of our first electric vehicle? Apply now!",
    "vehicle.join.button": "Join the Team",
    
    // Sponsors Page
    "sponsors.hero.title": "Our",
    "sponsors.hero.titleHighlight": "Sponsors",
    "sponsors.hero.description": "We are looking for valuable business partners who will support us in making our dreams come true.",
    "sponsors.tiers.platinum": "Platinum Sponsors",
    "sponsors.tiers.gold": "Gold Sponsors",
    "sponsors.tiers.silver": "Silver Sponsors",
    "sponsors.looking": "Looking for Sponsors!",
    "sponsors.looking.desc": "We need sponsors to turn our newly established team's first electric vehicle into reality.",
    "sponsors.why.title": "Why Become",
    "sponsors.why.titleHighlight": "a Sponsor",
    "sponsors.why.subtitle": "?",
    "sponsors.why.description": "Sponsoring EMUFSC is not just supporting a team, but investing in the future.",
    "sponsors.benefit.visibility": "Brand Visibility",
    "sponsors.benefit.visibility.desc": "Showcase your brand on our vehicle, team apparel, and social media.",
    "sponsors.benefit.csr": "Corporate Social Responsibility",
    "sponsors.benefit.csr.desc": "Demonstrate your responsibility by supporting education and sustainable technologies.",
    "sponsors.benefit.networking": "Networking Opportunities",
    "sponsors.benefit.networking.desc": "Meet industry professionals at competitions and events.",
    "sponsors.benefit.talent": "Talent Source",
    "sponsors.benefit.talent.desc": "Establish early contact with promising engineering students.",
    "sponsors.packages.title": "Sponsorship",
    "sponsors.packages.titleHighlight": "Packages",
    "sponsors.packages.description": "We offer different sponsorship options to suit your needs and budget.",
    "sponsors.package.popular": "Most Popular",
    "sponsors.cta.title": "Get in Touch",
    "sponsors.cta.description": "Contact our team to learn more about sponsorship opportunities and collaborate with the leaders of tomorrow's electric automotive industry.",
    "sponsors.cta.form": "Contact Form",
    "sponsors.cta.email": "Send Email",
    "sponsors.impact.title": "Impact of",
    "sponsors.impact.titleHighlight": "Sponsorship",
    "sponsors.impact.students": "Student Education",
    "sponsors.impact.reach": "Social Media Reach",
    "sponsors.impact.project": "Electric Vehicle Project",
    
    // Contact Page
    "contact.hero.title": "Get in",
    "contact.hero.titleHighlight": "Touch",
    "contact.hero.description": "Feel free to contact us with your questions, suggestions, or collaboration proposals.",
    "contact.info.address": "Address",
    "contact.info.email": "Email",
    "contact.info.phone": "Phone",
    "contact.form.title": "Write to",
    "contact.form.titleHighlight": "Us",
    "contact.form.name": "Your Name",
    "contact.form.email": "Your Email",
    "contact.form.subject": "Subject",
    "contact.form.subject.select": "Select subject",
    "contact.form.subject.general": "General Information",
    "contact.form.subject.membership": "Membership",
    "contact.form.subject.sponsorship": "Sponsorship",
    "contact.form.subject.media": "Media & Press",
    "contact.form.subject.other": "Other",
    "contact.form.message": "Your Message",
    "contact.form.submit": "Send Message",
    "contact.form.success": "Your message has been received! We will get back to you as soon as possible.",
    "contact.quick.title": "Quick",
    "contact.quick.titleHighlight": "Info",
    "contact.hours.title": "Working Hours",
    "contact.hours.weekday": "Monday - Friday: 09:00 - 18:00",
    "contact.hours.saturday": "Saturday: 10:00 - 16:00",
    "contact.hours.sunday": "Sunday: Closed",
    "contact.visit.title": "Visit Our Workshop",
    "contact.visit.description": "If you want to see our team and work closely, please make an appointment in advance. We would be happy to give you a tour and tell you about our projects.",
    "contact.visit.button": "Make an Appointment →",
    "contact.social.title": "Social Media",
    "contact.location.title": "Our",
    "contact.location.titleHighlight": "Location",
    "contact.faq.title": "Frequently Asked",
    "contact.faq.titleHighlight": "Questions",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("tr");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
